### ISSUE TITLE
Error filtering template: Notice: Undefined variable: precision

### ISSUE THREAD

**Issue by aloupfor** [ecommpro/custom-currency#3]
**Magento version**: 2.3.1
**Plugin version**: 1.0.1

I have the following error when I try to reach the front office:

>  Error filtering template: Notice: Undefined variable: precision in /app/vendor/ecommpro/module-custom-currency/Plugin/PriceCurrencyInterfacePlugin.php on line 17

There is a typo in `$precission` here: https://github.com/ecommpro/custom-currency/blob/master/Plugin/PriceCurrencyInterfacePlugin.php#L13 
(https://github.com/ecommpro/custom-currency/commit/23e4a57945d540e9cad14627f65dbf2041119948)

**Comment by manelio** [comment]
Just fixed in version 1.0.3.

**Comment by aloupfor** [comment]
Thank you for solving the issue.
